/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pipe-room.glb -t -K 
*/

import { useGLTF } from '@react-three/drei'
import { JSX } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_2001: THREE.Mesh
    Cube: THREE.Mesh
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/pipe-room.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group>
        <group>
          <group>
            <mesh name="pipeline-pipe-primary" geometry={nodes.Object_2.geometry}  >
              <meshStandardMaterial color={'#202020'} transparent opacity={0.1} side={THREE.BackSide} />
              {/* <Outlines thickness={0.001} color="hotpink"  /> */}

            </mesh>
            <mesh name="pipeline-pipe-secondary" geometry={nodes.Object_2001.geometry} material={nodes.Object_2001.material} >
              <meshStandardMaterial color={'#202020'} transparent opacity={0.1} side={THREE.BackSide} />

              {/* <Outlines thickness={0.0001} color="hotpink"  /> */}

            </mesh>
          </group>
        </group>
        <mesh name="pipeline-room-shell" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[5, 0, 0]} scale={[2, 1, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/pipe-room.glb')
