/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.glb -t -K 
*/

import { useGLTF } from '@react-three/drei'
import { type ThreeEvent, useFrame, useThree } from '@react-three/fiber'
import { JSX, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { InkEdges, toInkEdges } from './InkEdges'
import { ProjectPanels } from './ProjectPanels'
import { projects, type Project } from './projects'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    room: THREE.Mesh
    columns: THREE.Mesh
  }
  materials: {
    Cardboard: THREE.MeshStandardMaterial
  }
}

export const COLUMN_MESH_OFFSET_Y = 1.3725
export const COLUMN_MESH_SCALE_Y = 0.25
export const COLUMN_SPACING = 5.2
export const FIRST_COLUMN_CENTER_Y = -2.8725
export const COLUMN_SYSTEM_OFFSET_Y = -1.8725
export const PROJECTS_PER_COLUMN = 4
export const getProjectColumnCount = (projectCount: number) => Math.floor(projectCount / PROJECTS_PER_COLUMN) + 1
const COLUMN_PIVOT_X = -0.21
const COLUMN_PIVOT_Z = 0.03
const COLUMN_MESH_OFFSET_X = 0.21
const COLUMN_MESH_OFFSET_Z = -0.03
const QUARTER_TURN = Math.PI / 2
const DRAG_DISTANCE_PER_TURN = 120
const MIN_DRAG_DISTANCE = 28
const HALF_TURN_DISTANCE = 190
const HALF_TURN_VELOCITY = 1.1
const MOBILE_ROTATION_BREAKPOINT = 640
const MOBILE_PROJECT_ROTATIONS = [-24, -22, -10, 0].map(THREE.MathUtils.degToRad)
const TOUCH_SCROLL_INTENT_DISTANCE = 12
const TOUCH_AXIS_DOMINANCE = 1.1
const ROTATION_SNAP_EPSILON = THREE.MathUtils.degToRad(0.12)
const ROTATION_MATRIX_EPSILON = 0.00001
const MOBILE_SETTLE_DAMPING = 5
const DESKTOP_SETTLE_DAMPING = 3

function getMobileProjectRotation(rotation: number) {
  const projectIndex = ((-Math.round(rotation / QUARTER_TURN)) % PROJECTS_PER_COLUMN + PROJECTS_PER_COLUMN) % PROJECTS_PER_COLUMN
  return MOBILE_PROJECT_ROTATIONS[projectIndex] ?? 0
}

type PointerCaptureTarget = {
  setPointerCapture: (pointerId: number) => void
  releasePointerCapture: (pointerId: number) => void
}

type GestureIntent = 'pending' | 'rotate' | 'scroll'

function isTouchEvent(event: ThreeEvent<PointerEvent>) {
  return event.pointerType === 'touch' || event.nativeEvent.pointerType === 'touch'
}

type ColumnSectionProps = {
  geometry: THREE.BufferGeometry
  edges: THREE.EdgesGeometry
  centerY: number
  columnIndex: number
  sectionProjects: Project[]
	onAnchorChange: (columnIndex: number, x: number, z: number) => void
	onColumnMotion: (velocity: number, direction: number) => void
	reducedPerformance: boolean
}

function ColumnSection({ geometry, edges, centerY, columnIndex, sectionProjects, onAnchorChange, onColumnMotion, reducedPerformance }: ColumnSectionProps) {
  const viewportWidth = useThree((state) => state.size.width)
  const initialRestingRotation = viewportWidth <= MOBILE_ROTATION_BREAKPOINT ? getMobileProjectRotation(0) : 0
  const columns = useRef<THREE.Group>(null)
  const columnCenter = useRef<THREE.Group>(null)
  const anchorPosition = useRef(new THREE.Vector3())
  const geometryCenter = useMemo(() => {
    geometry.computeBoundingBox()
    const center = new THREE.Vector3()
    geometry.boundingBox?.getCenter(center)
    center.y *= COLUMN_MESH_SCALE_Y
    return center
  }, [geometry])
  const targetRotation = useRef(0)
  const dragOriginRotation = useRef(0)
  const dragPreviewRotation = useRef(0)
  const dragStartX = useRef(0)
  const dragStartY = useRef(0)
  const dragStartTime = useRef(0)
  const lastPointerX = useRef(0)
  const lastPointerTime = useRef(0)
  const isDragging = useRef(false)
  const gestureIntent = useRef<GestureIntent>('pending')
  const capturedPointerId = useRef<number | null>(null)
  const previousAppliedRotation = useRef(Number.NaN)

  const capturePointer = (event: ThreeEvent<PointerEvent>) => {
    if (capturedPointerId.current === event.pointerId) return
    const pointerTarget = event.target as unknown as PointerCaptureTarget
    pointerTarget.setPointerCapture(event.pointerId)
    capturedPointerId.current = event.pointerId
  }

  const releasePointer = (event: ThreeEvent<PointerEvent>) => {
    if (capturedPointerId.current !== event.pointerId) return
    const pointerTarget = event.target as unknown as PointerCaptureTarget
    pointerTarget.releasePointerCapture(event.pointerId)
    capturedPointerId.current = null
  }

  const rotateFromDrag = (event: ThreeEvent<PointerEvent>) => {
    if (!isDragging.current) return

    const distance = event.nativeEvent.clientX - dragStartX.current
    const verticalDistance = event.nativeEvent.clientY - dragStartY.current

    if (isTouchEvent(event) && gestureIntent.current === 'pending') {
      const horizontalDelta = Math.abs(distance)
      const verticalDelta = Math.abs(verticalDistance)

      if (verticalDelta >= TOUCH_SCROLL_INTENT_DISTANCE && verticalDelta > horizontalDelta * TOUCH_AXIS_DOMINANCE) {
        gestureIntent.current = 'scroll'
        dragPreviewRotation.current = dragOriginRotation.current
        isDragging.current = false
        releasePointer(event)
        return
      }

      if (horizontalDelta < TOUCH_SCROLL_INTENT_DISTANCE || horizontalDelta <= verticalDelta * TOUCH_AXIS_DOMINANCE) {
        return
      }

      gestureIntent.current = 'rotate'
      capturePointer(event)
    }

    if (gestureIntent.current !== 'rotate') return

    dragPreviewRotation.current = dragOriginRotation.current + (distance / DRAG_DISTANCE_PER_TURN) * QUARTER_TURN
    lastPointerX.current = event.nativeEvent.clientX
    lastPointerTime.current = event.nativeEvent.timeStamp
  }

  const handlePointerDown = (event: ThreeEvent<PointerEvent>) => {
    event.stopPropagation()
    isDragging.current = true
    gestureIntent.current = isTouchEvent(event) ? 'pending' : 'rotate'
    dragStartX.current = event.nativeEvent.clientX
    dragStartY.current = event.nativeEvent.clientY
    dragStartTime.current = event.nativeEvent.timeStamp
    lastPointerX.current = event.nativeEvent.clientX
    lastPointerTime.current = event.nativeEvent.timeStamp
    dragOriginRotation.current = targetRotation.current
    dragPreviewRotation.current = targetRotation.current
    if (gestureIntent.current === 'rotate') capturePointer(event)
  }

  const handlePointerUp = (event: ThreeEvent<PointerEvent>) => {
    event.stopPropagation()
    if (!isDragging.current || gestureIntent.current !== 'rotate') {
      isDragging.current = false
      gestureIntent.current = 'pending'
      releasePointer(event)
      return
    }

    const distance = event.nativeEvent.clientX - dragStartX.current
    const totalDuration = Math.max(event.nativeEvent.timeStamp - dragStartTime.current, 1)
    const sampleDuration = Math.max(event.nativeEvent.timeStamp - lastPointerTime.current, 1)
    const sampledVelocity = (event.nativeEvent.clientX - lastPointerX.current) / sampleDuration
    const averageVelocity = distance / totalDuration
    const velocity = Math.abs(sampledVelocity) > Math.abs(averageVelocity) ? sampledVelocity : averageVelocity

    if (Math.abs(distance) >= MIN_DRAG_DISTANCE) {
      const direction = Math.sign(distance)
      const turns = Math.abs(distance) >= HALF_TURN_DISTANCE || Math.abs(velocity) >= HALF_TURN_VELOCITY ? 2 : 1
      targetRotation.current = dragOriginRotation.current + direction * turns * QUARTER_TURN
		const distanceStrength = THREE.MathUtils.clamp(Math.abs(distance) / HALF_TURN_DISTANCE, 0, 1)
		const velocityStrength = 1 - Math.exp(-Math.abs(velocity) * 1.5)
		const rotationStrength = THREE.MathUtils.clamp(distanceStrength * 0.7 + velocityStrength * 0.3, 0, 1)
		onColumnMotion(rotationStrength, direction)
    } else {
      targetRotation.current = dragOriginRotation.current
    }

    isDragging.current = false
    gestureIntent.current = 'pending'
    releasePointer(event)
  }

  const handlePointerCancel = () => {
    if (isDragging.current && gestureIntent.current === 'rotate') {
      targetRotation.current = dragOriginRotation.current
    }
    isDragging.current = false
    gestureIntent.current = 'pending'
    capturedPointerId.current = null
  }

  useFrame((_, delta) => {
    if (!columns.current) return

    const baseRotation = isDragging.current ? dragPreviewRotation.current : targetRotation.current
    const restingRotation = viewportWidth <= MOBILE_ROTATION_BREAKPOINT
      ? getMobileProjectRotation(isDragging.current ? dragOriginRotation.current : targetRotation.current)
      : 0
    const rotation = baseRotation + restingRotation
    const rotationError = Math.abs(rotation - columns.current.rotation.y)
    if (!isDragging.current && rotationError <= ROTATION_SNAP_EPSILON) {
      columns.current.rotation.y = rotation
    } else {
      const settleDamping = viewportWidth <= MOBILE_ROTATION_BREAKPOINT
        ? MOBILE_SETTLE_DAMPING
        : DESKTOP_SETTLE_DAMPING
      columns.current.rotation.y = THREE.MathUtils.damp(
        columns.current.rotation.y,
        rotation,
        isDragging.current ? 4 : settleDamping,
        delta,
      )
    }

    if (Math.abs(columns.current.rotation.y - previousAppliedRotation.current) <= ROTATION_MATRIX_EPSILON) return
    previousAppliedRotation.current = columns.current.rotation.y
    columns.current.updateWorldMatrix(true, false)

    if (!columnCenter.current) return
    anchorPosition.current.copy(geometryCenter)
    columnCenter.current.localToWorld(anchorPosition.current)
    onAnchorChange(columnIndex, anchorPosition.current.x, anchorPosition.current.z)
  })

  return (
    <>
      <mesh
        position={[1.2, centerY, 0]}
        rotation={[0, Math.PI / 2, 0]}
        onPointerDown={handlePointerDown}
        onPointerMove={rotateFromDrag}
        onPointerUp={handlePointerUp}
        onPointerCancel={handlePointerCancel}
        onLostPointerCapture={handlePointerCancel}
      >
        <planeGeometry args={[4.8, 3.8]} />
        <meshBasicMaterial transparent opacity={0} depthWrite={false} />
      </mesh>
      <group ref={columns} position={[COLUMN_PIVOT_X, centerY, COLUMN_PIVOT_Z]} rotation={[0, initialRestingRotation, 0]}>
        <group ref={columnCenter} position={[COLUMN_MESH_OFFSET_X, COLUMN_MESH_OFFSET_Y, COLUMN_MESH_OFFSET_Z]}>
          <mesh geometry={geometry} castShadow receiveShadow scale={[1, COLUMN_MESH_SCALE_Y, 1]}>
            <meshStandardMaterial color="#27282b"  />
          </mesh>
          <InkEdges edges={edges} scale={[1, COLUMN_MESH_SCALE_Y, 1]} />
          <ProjectPanels
            geometry={geometry}
            projects={sectionProjects}
            scaleY={COLUMN_MESH_SCALE_Y}
            reducedPerformance={reducedPerformance}
          />
        </group>
      </group>
    </>
  )
}

function ColumnSystem({ geometry, edges, onAnchorChange, onColumnMotion, reducedPerformance }: Pick<ColumnSectionProps, 'geometry' | 'edges' | 'onAnchorChange' | 'onColumnMotion' | 'reducedPerformance'>) {
  const projectSections = useMemo(() => Array.from(
    { length: getProjectColumnCount(projects.length) },
    (_, columnIndex) => projects.slice(
      columnIndex * PROJECTS_PER_COLUMN,
      (columnIndex + 1) * PROJECTS_PER_COLUMN,
    ),
  ), [])

  return projectSections.map((sectionProjects, columnIndex) => (
    <ColumnSection
      key={columnIndex}
      geometry={geometry}
      edges={edges}
      centerY={FIRST_COLUMN_CENTER_Y - columnIndex * COLUMN_SPACING}
      columnIndex={columnIndex}
      sectionProjects={sectionProjects}
      onAnchorChange={onAnchorChange}
      onColumnMotion={onColumnMotion}
      reducedPerformance={reducedPerformance}
    />
  ))
}

export function Room({ onAnchorChange, onColumnMotion, reducedPerformance, ...props }: JSX.IntrinsicElements['group'] & {
	onAnchorChange: (columnIndex: number, x: number, z: number) => void
	onColumnMotion: (velocity: number, direction: number) => void
	reducedPerformance: boolean
}) {
  const { nodes, materials } = useGLTF('/room2.glb') as unknown as GLTFResult

  const roomEdges = useMemo(() => toInkEdges(nodes.room.geometry), [nodes.room.geometry])
  const columnsEdges = useMemo(() => toInkEdges(nodes.columns.geometry), [nodes.columns.geometry])

  return (
    <group {...props} dispose={null}>
      <group>
        <group >
          <mesh geometry={nodes.room.geometry} material={materials.Cardboard} castShadow receiveShadow scale={[1.2, 1.3, 1.2]}>
            <meshStandardMaterial color="#202020"  />
          </mesh>
          <InkEdges edges={roomEdges} scale={[1.2, 1.3, 1.2]} />
        </group>
		<group position={[0, COLUMN_SYSTEM_OFFSET_Y, 0]}>
          <ColumnSystem
            geometry={nodes.columns.geometry}
            edges={columnsEdges}
            onAnchorChange={onAnchorChange}
            onColumnMotion={onColumnMotion}
            reducedPerformance={reducedPerformance}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/room.glb')
