/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.glb -t -K 
*/

import { useGLTF } from '@react-three/drei'
import { type ThreeEvent, useFrame, useThree } from '@react-three/fiber'
import { JSX, useEffect, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { ProjectPanels } from './ProjectPanels'
import { projects, type Project } from './projects'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    room: THREE.Mesh
    columns: THREE.Mesh
  }
  materials: {
    Cardboard: THREE.MeshStandardMaterial
  }
}

const INK_LINE_VERTEX_SHADER = `
  attribute vec3 aStart;
  attribute vec3 aEnd;
  attribute vec2 aCorner;

  uniform vec2 uResolution;
  uniform float uLineWidth;

  void main() {
    vec4 start = projectionMatrix * modelViewMatrix * vec4(aStart, 1.0);
    vec4 end = projectionMatrix * modelViewMatrix * vec4(aEnd, 1.0);
    vec2 startNdc = start.xy / start.w;
    vec2 endNdc = end.xy / end.w;
    vec2 direction = normalize(endNdc - startNdc);
    vec2 normal = vec2(-direction.y, direction.x);
    vec2 offset = normal * aCorner.x * uLineWidth / uResolution;
    vec4 clipPosition = mix(start, end, aCorner.y);

    clipPosition.xy += offset * clipPosition.w;
    clipPosition.z -= 0.0015 * clipPosition.w;
    gl_Position = clipPosition;
  }
`

const INK_LINE_FRAGMENT_SHADER = `
  uniform vec3 uLineColor;

  void main() {
  vec3 LineColor = uLineColor + vec3(1.0);
    gl_FragColor = vec4(LineColor, 1.0);
  }
`

function toInkEdges(source: THREE.BufferGeometry): THREE.EdgesGeometry {
  return new THREE.EdgesGeometry(source, 30)
}

function toThickLineGeometry(edges: THREE.EdgesGeometry): THREE.BufferGeometry {
  const positions = edges.getAttribute('position')
  const segmentCount = positions.count / 2
  const starts = new Float32Array(segmentCount * 4 * 3)
  const ends = new Float32Array(segmentCount * 4 * 3)
  const corners = new Float32Array(segmentCount * 4 * 2)
  const indices = new Uint32Array(segmentCount * 6)

  for (let segment = 0; segment < segmentCount; segment += 1) {
    const start = new THREE.Vector3().fromBufferAttribute(positions, segment * 2)
    const end = new THREE.Vector3().fromBufferAttribute(positions, segment * 2 + 1)
    const vertexOffset = segment * 4
    const indexOffset = segment * 6

    for (let vertex = 0; vertex < 4; vertex += 1) {
      starts.set(start.toArray(), (vertexOffset + vertex) * 3)
      ends.set(end.toArray(), (vertexOffset + vertex) * 3)
    }

    corners.set([-1, 0, 1, 0, -1, 1, 1, 1], segment * 8)
    indices.set([vertexOffset, vertexOffset + 1, vertexOffset + 2, vertexOffset + 2, vertexOffset + 1, vertexOffset + 3], indexOffset)
  }

  const geometry = new THREE.BufferGeometry()
  geometry.setAttribute('aStart', new THREE.BufferAttribute(starts, 3))
  geometry.setAttribute('aEnd', new THREE.BufferAttribute(ends, 3))
  geometry.setAttribute('aCorner', new THREE.BufferAttribute(corners, 2))
  geometry.setIndex(new THREE.BufferAttribute(indices, 1))
  return geometry
}

function InkEdges({ edges, scale, position }: { edges: THREE.EdgesGeometry, scale?: [number, number, number], position?: [number, number, number] }) {
  const gl = useThree((state) => state.gl)
  const size = useThree((state) => state.size)
  const geometry = useMemo(() => toThickLineGeometry(edges), [edges])
  const uniforms = useMemo(() => ({
    uResolution: { value: new THREE.Vector2() },
    uLineWidth: { value: 3 },
    uLineColor: { value: new THREE.Color('#000000') },
  }), [])

  useEffect(() => {
    uniforms.uResolution.value.set(size.width * gl.getPixelRatio(), size.height * gl.getPixelRatio())
  }, [gl, size.height, size.width, uniforms])

  return (
    <mesh geometry={geometry} renderOrder={1} frustumCulled={false} scale={scale} position={position}>
      <shaderMaterial
        vertexShader={INK_LINE_VERTEX_SHADER}
        fragmentShader={INK_LINE_FRAGMENT_SHADER}
        uniforms={uniforms}
        depthWrite={false}
        depthTest
        side={THREE.DoubleSide}
      />
    </mesh>
  )
}

export const COLUMN_MESH_OFFSET_Y = 1.3725
export const COLUMN_SPACING = 2.7
export const PROJECTS_PER_COLUMN = 4
export const getProjectColumnCount = (projectCount: number) => Math.floor(projectCount / PROJECTS_PER_COLUMN) + 1
const COLUMN_PIVOT_X = -0.21
const COLUMN_PIVOT_Z = 0.03
const COLUMN_MESH_OFFSET_X = 0.21
const COLUMN_MESH_OFFSET_Z = -0.03
const QUARTER_TURN = Math.PI / 2
const DRAG_DISTANCE_PER_TURN = 120
const MIN_DRAG_DISTANCE = 28
const HALF_TURN_DISTANCE = 190
const HALF_TURN_VELOCITY = 1.1

type PointerCaptureTarget = {
  setPointerCapture: (pointerId: number) => void
  releasePointerCapture: (pointerId: number) => void
}

type ColumnSectionProps = {
  geometry: THREE.BufferGeometry
  edges: THREE.EdgesGeometry
  centerY: number
  columnIndex: number
  sectionProjects: Project[]
  onAnchorChange: (columnIndex: number, x: number, z: number) => void
}

function ColumnSection({ geometry, edges, centerY, columnIndex, sectionProjects, onAnchorChange }: ColumnSectionProps) {
  const columns = useRef<THREE.Group>(null)
  const columnCenter = useRef<THREE.Group>(null)
  const anchorPosition = useRef(new THREE.Vector3())
  const geometryCenter = useMemo(() => {
    geometry.computeBoundingBox()
    const center = new THREE.Vector3()
    geometry.boundingBox?.getCenter(center)
    center.y *= 0.25
    return center
  }, [geometry])
  const targetRotation = useRef(0)
  const dragOriginRotation = useRef(0)
  const dragPreviewRotation = useRef(0)
  const dragStartX = useRef(0)
  const dragStartTime = useRef(0)
  const lastPointerX = useRef(0)
  const lastPointerTime = useRef(0)
  const isDragging = useRef(false)

  const rotateFromDrag = (event: ThreeEvent<PointerEvent>) => {
    if (!isDragging.current) return

    const distance = event.nativeEvent.clientX - dragStartX.current
    dragPreviewRotation.current = dragOriginRotation.current + (distance / DRAG_DISTANCE_PER_TURN) * QUARTER_TURN
    lastPointerX.current = event.nativeEvent.clientX
    lastPointerTime.current = event.nativeEvent.timeStamp
  }

  const handlePointerDown = (event: ThreeEvent<PointerEvent>) => {
    event.stopPropagation()
    isDragging.current = true
    dragStartX.current = event.nativeEvent.clientX
    dragStartTime.current = event.nativeEvent.timeStamp
    lastPointerX.current = event.nativeEvent.clientX
    lastPointerTime.current = event.nativeEvent.timeStamp
    dragOriginRotation.current = targetRotation.current
    dragPreviewRotation.current = targetRotation.current
    const pointerTarget = event.target as unknown as PointerCaptureTarget
    pointerTarget.setPointerCapture(event.pointerId)
  }

  const handlePointerUp = (event: ThreeEvent<PointerEvent>) => {
    event.stopPropagation()
    const distance = event.nativeEvent.clientX - dragStartX.current
    const totalDuration = Math.max(event.nativeEvent.timeStamp - dragStartTime.current, 1)
    const sampleDuration = Math.max(event.nativeEvent.timeStamp - lastPointerTime.current, 1)
    const sampledVelocity = (event.nativeEvent.clientX - lastPointerX.current) / sampleDuration
    const averageVelocity = distance / totalDuration
    const velocity = Math.abs(sampledVelocity) > Math.abs(averageVelocity) ? sampledVelocity : averageVelocity

    if (Math.abs(distance) >= MIN_DRAG_DISTANCE) {
      const direction = Math.sign(distance)
      const turns = Math.abs(distance) >= HALF_TURN_DISTANCE || Math.abs(velocity) >= HALF_TURN_VELOCITY ? 2 : 1
      targetRotation.current = dragOriginRotation.current + direction * turns * QUARTER_TURN
    } else {
      targetRotation.current = dragOriginRotation.current
    }

    isDragging.current = false
    const pointerTarget = event.target as unknown as PointerCaptureTarget
    pointerTarget.releasePointerCapture(event.pointerId)
  }

  const handlePointerCancel = () => {
    targetRotation.current = dragOriginRotation.current
    isDragging.current = false
  }

  useFrame((_, delta) => {
    if (!columns.current) return

    const rotation = isDragging.current ? dragPreviewRotation.current : targetRotation.current
    columns.current.rotation.y = THREE.MathUtils.damp(columns.current.rotation.y, rotation, isDragging.current ? 4 : 2, delta)
    columns.current.updateWorldMatrix(true, false)

    if (!columnCenter.current) return
    anchorPosition.current.copy(geometryCenter)
    columnCenter.current.localToWorld(anchorPosition.current)
    onAnchorChange(columnIndex, anchorPosition.current.x, anchorPosition.current.z)
  })

  return (
    <>
      <mesh
        position={[1.2, centerY, 0]}
        rotation={[0, Math.PI / 2, 0]}
        onPointerDown={handlePointerDown}
        onPointerMove={rotateFromDrag}
        onPointerUp={handlePointerUp}
        onPointerCancel={handlePointerCancel}
        onLostPointerCapture={handlePointerCancel}
      >
        <planeGeometry args={[4.8, 3.8]} />
        <meshBasicMaterial transparent opacity={0} depthWrite={false} />
      </mesh>
      <group ref={columns} position={[COLUMN_PIVOT_X, centerY, COLUMN_PIVOT_Z]}>
        <group ref={columnCenter} position={[COLUMN_MESH_OFFSET_X, COLUMN_MESH_OFFSET_Y, COLUMN_MESH_OFFSET_Z]}>
          <mesh geometry={geometry} castShadow receiveShadow scale={[1, 0.25, 1]}>
            <meshStandardMaterial color="#202020" polygonOffset polygonOffsetFactor={1} polygonOffsetUnits={1} />
          </mesh>
          <InkEdges edges={edges} scale={[1, 0.25, 1]} />
          <ProjectPanels geometry={geometry} projects={sectionProjects} />
        </group>
      </group>
    </>
  )
}

function ColumnSystem({ geometry, edges, onAnchorChange }: Pick<ColumnSectionProps, 'geometry' | 'edges' | 'onAnchorChange'>) {
  const projectSections = useMemo(() => Array.from(
    { length: getProjectColumnCount(projects.length) },
    (_, columnIndex) => projects.slice(
      columnIndex * PROJECTS_PER_COLUMN,
      (columnIndex + 1) * PROJECTS_PER_COLUMN,
    ),
  ), [])

  return projectSections.map((sectionProjects, columnIndex) => (
    <ColumnSection
      key={columnIndex}
      geometry={geometry}
      edges={edges}
      centerY={-2.8725 - columnIndex * COLUMN_SPACING}
      columnIndex={columnIndex}
      sectionProjects={sectionProjects}
      onAnchorChange={onAnchorChange}
    />
  ))
}

export function Room({ onAnchorChange, ...props }: JSX.IntrinsicElements['group'] & { onAnchorChange: (columnIndex: number, x: number, z: number) => void }) {
  const { nodes, materials } = useGLTF('/room2.glb') as unknown as GLTFResult

  const roomEdges = useMemo(() => toInkEdges(nodes.room.geometry), [nodes.room.geometry])
  const columnsEdges = useMemo(() => toInkEdges(nodes.columns.geometry), [nodes.columns.geometry])

  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.room.geometry} material={materials.Cardboard} castShadow receiveShadow>
          <meshStandardMaterial color="#202020" polygonOffset polygonOffsetFactor={1} polygonOffsetUnits={1} />
        </mesh>
        <InkEdges edges={roomEdges} scale={[1, 1, 1]} />
        <ColumnSystem geometry={nodes.columns.geometry} edges={columnsEdges} onAnchorChange={onAnchorChange} />
      </group>
    </group>
  )
}

useGLTF.preload('/room.glb')
